services:
  user_service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    networks:
      - server_network
    ports:
      - 8080:8080
    volumes:
      - ./services/user-service:/app 
  transfer_service:
    build:
      context: ./services/transfer-service
      dockerfile: Dockerfile
    networks:
      - server_network
    ports:
      - 8081:8081
    volumes:
      - ./services/transfer-service:/app 

networks:
  server_network:
    driver: bridge