services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - server_network
  user_service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    networks:
      - server_network
    ports:
      - 8080:8080
    volumes:
      - ./services/user-service:/app 
  transfer_service:
    build:
      context: ./services/transfer-service
      dockerfile: Dockerfile
    depends_on:
      - user_service
    networks:
      - server_network
    ports:
      - 8081:8081
    volumes:
      - ./services/transfer-service:/app 

networks:
  server_network:
    driver: bridge